services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    hostname: casper-alpha
    environment:
      - TS_EXTRA_ARGS=--advertise-tags=tag:ci
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ./tailscale/state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped
    networks:
      casper:
        ipv4_address: 192.168.0.2

  nginx:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx
    depends_on:
      - tailscale
    restart: unless-stopped
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      - ./ssl:/etc/nginx/ssl/selfcerts
      - ./nginx/custom:/etc/nginx/custom
    network_mode: "container:tailscale"

  adguard:
    image: adguard/adguardhome
    container_name: adguard
    depends_on: 
      - tailscale
    network_mode: "container:tailscale"
    volumes:
      - ./adguard:/opt/adguardhome/work
      - ./adguard/conf:/opt/adguardhome/conf
      - ./ssl:/opt/adguardhome/certs:ro
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:lts
    container_name: portainer
    depends_on:
      - tailscale
    networks:
      casper:
        ipv4_address: 192.168.0.10
    ports:
      - "9443:9443"   # HTTPS Web UI
      - "8000:8000"   # Agent Tunnel (for remote management)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped

  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    depends_on:
      - tailscale
    networks:
      casper:
        ipv4_address: 192.168.0.11
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=HST
    volumes:
      - ./heimdall/config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
  
  mc-lsv:
    image: itzg/minecraft-server:latest
    container_name: minecraft-lsv
    networks:
      casper:
        ipv4_address: 192.168.0.101
    tty: true
    stdin_open: true
    environment:
      EULA: "TRUE"
      TYPE: PAPER
    volumes:
      - minecraft_lsv:/data
      - /var/lib/minecraft/lsv/plugins:/plugins
    depends_on:
      - tailscale
    restart: unless-stopped  
  
  mc-modded:
    image: itzg/minecraft-server:latest
    container_name: minecraft-modded
    networks:
      casper:
        ipv4_address: 192.168.0.102
    tty: true
    stdin_open: true
    environment:
      EULA: "TRUE"
    volumes:
      - minecraft_modded_1:/data
      - /var/lib/minecraft/modded/plugins:/plugins
      - /var/lib/minecraft/modded/mods:/mods
    depends_on:
      - tailscale
    restart: unless-stopped  

  mc-router:
    image: haveachin/infrared:latest
    container_name: minecraft-router
    restart: always
    networks:
      casper:
        ipv4_address: 192.168.0.100
    ports:
    - "25565:25565/tcp"
    volumes:
      - ./data/infrared:/etc/infrared
    command:
      - "--log-level=debug"

networks:
  casper:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/16
          gateway: 192.168.0.1

volumes:
  minecraft_lsv:
    external: true
  minecraft_modded_1:
    external: true
  portainer_data:
    external: true
